import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#dc2626",
        "on-secondary": "#ffffff",
        "secondary-container": "#d8e8c8",
        "surface-bright": "#f5f3ef",
        "on-secondary-fixed-variant": "#3a5a3a",
        "primary-fixed": "#c8d8b8",
        "on-surface-variant": "#4a5240",
        surface: "#f5f3ef",
        "on-primary-fixed-variant": "#2d4a2d",
        outline: "#7a8a6a",
        "surface-container": "#e8e5de",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#4a3a20",
        "on-error-container": "#991b1b",
        "surface-variant": "#dedad2",
        "tertiary-fixed-dim": "#c8b890",
        "on-tertiary": "#ffffff",
        tertiary: "#3a5a3a",
        "surface-container-high": "#dedad2",
        "primary-fixed-dim": "#a3b18a",
        "on-tertiary-fixed": "#1a0a00",
        "surface-container-highest": "#d4d0c8",
        "on-surface": "#1a2010",
        primary: "#344e41",
        "surface-dim": "#c8c4bc",
        "on-primary-container": "#a3b18a",
        "primary-container": "#3a5a3a",
        "error-container": "#fee2e2",
        "surface-container-low": "#f0ede6",
        "inverse-surface": "#2a3020",
        "on-tertiary-container": "#8a7040",
        "on-secondary-fixed": "#1a2a1a",
        background: "#dad7cd",
        "on-background": "#1a2010",
        "surface-tint": "#588157",
        "secondary-fixed": "#c8d8b8",
        "outline-variant": "#c0bdb5",
        "surface-container-lowest": "#faf8f4",
        "inverse-on-surface": "#f0ede6",
        "on-error": "#ffffff",
        "tertiary-fixed": "#e8dfc0",
        "secondary-fixed-dim": "#a3b18a",
        "tertiary-container": "#2a1a00",
        "on-primary-fixed": "#0a1a0a",
        "on-secondary-container": "#2d4a2d",
        "inverse-primary": "#a3b18a",
        secondary: "#588157",
        "success-neon": "#a3b18a",
        "navy-custom": "#344e41",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-mono": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;

export default config;
