import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#dc2626",
        "on-secondary": "#ffffff",
        "secondary-container": "#dcfce7",
        "surface-bright": "#f0fdf4",
        "on-secondary-fixed-variant": "#166534",
        "primary-fixed": "#bbf7d0",
        "on-surface-variant": "#374151",
        surface: "#f0fdf4",
        "on-primary-fixed-variant": "#14532d",
        outline: "#6b7280",
        "surface-container": "#dcfce7",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#713f12",
        "on-error-container": "#991b1b",
        "surface-variant": "#d1fae5",
        "tertiary-fixed-dim": "#fde68a",
        "on-tertiary": "#ffffff",
        tertiary: "#065f46",
        "surface-container-high": "#bbf7d0",
        "primary-fixed-dim": "#86efac",
        "on-tertiary-fixed": "#1a0a00",
        "surface-container-highest": "#a7f3d0",
        "on-surface": "#111827",
        primary: "#14532d",
        "surface-dim": "#a7f3d0",
        "on-primary-container": "#4ade80",
        "primary-container": "#166534",
        "error-container": "#fee2e2",
        "surface-container-low": "#f0fdf4",
        "inverse-surface": "#1f2937",
        "on-tertiary-container": "#d97706",
        "on-secondary-fixed": "#052e16",
        background: "#f0fdf4",
        "on-background": "#111827",
        "surface-tint": "#16a34a",
        "secondary-fixed": "#bbf7d0",
        "outline-variant": "#d1d5db",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f9fafb",
        "on-error": "#ffffff",
        "tertiary-fixed": "#fef3c7",
        "secondary-fixed-dim": "#86efac",
        "tertiary-container": "#1a0a00",
        "on-primary-fixed": "#052e16",
        "on-secondary-container": "#14532d",
        "inverse-primary": "#86efac",
        secondary: "#16a34a",
        "success-neon": "#22c55e",
        "navy-custom": "#166534",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-mono": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;

export default config;
