import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "secondary-container": "#d0e1fb",
        "surface-bright": "#fcf8fa",
        "on-secondary-fixed-variant": "#38485d",
        "primary-fixed": "#dae2fd",
        "on-surface-variant": "#45464d",
        surface: "#fcf8fa",
        "on-primary-fixed-variant": "#3f465c",
        outline: "#76777d",
        "surface-container": "#f0edef",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#574425",
        "on-error-container": "#93000a",
        "surface-variant": "#e4e2e4",
        "tertiary-fixed-dim": "#dec29a",
        "on-tertiary": "#ffffff",
        tertiary: "#0f172a",
        "surface-container-high": "#eae7e9",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#271901",
        "surface-container-highest": "#e4e2e4",
        "on-surface": "#1b1b1d",
        primary: "#0f172a",
        "surface-dim": "#dcd9db",
        "on-primary-container": "#7c839b",
        "primary-container": "#1e293b",
        "error-container": "#ffdad6",
        "surface-container-low": "#f6f3f5",
        "inverse-surface": "#303032",
        "on-tertiary-container": "#98805d",
        "on-secondary-fixed": "#0b1c30",
        background: "#fcf8fa",
        "on-background": "#1b1b1d",
        "surface-tint": "#565e74",
        "secondary-fixed": "#d3e4fe",
        "outline-variant": "#c6c6cd",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f3f0f2",
        "on-error": "#ffffff",
        "tertiary-fixed": "#fcdeb5",
        "secondary-fixed-dim": "#b7c8e1",
        "tertiary-container": "#271901",
        "on-primary-fixed": "#131b2e",
        "on-secondary-container": "#54647a",
        "inverse-primary": "#bec6e0",
        secondary: "#505f76",
        "success-neon": "#39FF14",
        "navy-custom": "#0f172a",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-mono": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
